package com.timed.data.models;

import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.ServerTimestamp;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Represents an Event in the Calendar
 * This model follows the Firestore database architecture
 */
public class EventModel implements Serializable {
    @SerializedName("id")
    private String id; // Auto-generated by Firestore

    @SerializedName("calendar_id")
    private String calendarId; // Foreign key to calendar

    @SerializedName("title")
    private String title;

    @SerializedName("description")
    private String description;

    @SerializedName("start_time")
    private long startTime; // Unix timestamp

    @SerializedName("end_time")
    private long endTime; // Unix timestamp

    @SerializedName("all_day")
    private boolean allDay;

    @SerializedName("location")
    private String location;

    @SerializedName("notes")
    private String notes;

    @SerializedName("recurrence_rule")
    private String recurrenceRule; // iCal format (e.g., "FREQ=WEEKLY;BYDAY=MO")

    @SerializedName("recurrence_exceptions")
    private List<Long> recurrenceExceptions; // timestamps of exceptions

    @SerializedName("instance_of")
    private String instanceOf; // ID of parent recurring event (if modified instance)

    @SerializedName("participant_ids")
    private List<String> participantIds;

    @SerializedName("participant_statuses")
    private Map<String, String> participantStatuses; // uid -> status mapping

    @SerializedName("reminders")
    private List<Reminder> reminders;

    @SerializedName("attachments")
    private List<Attachment> attachments;

    @SerializedName("color")
    private String color; // Hex color code

    @SerializedName("created_at")
    @ServerTimestamp
    private Date createdAt;

    @SerializedName("updated_at")
    @ServerTimestamp
    private Date updatedAt;

    @SerializedName("created_by")
    private String createdBy; // UID of creator

    @SerializedName("visibility")
    private String visibility; // "public" or "private"

    public EventModel() {
        this.participantIds = new ArrayList<>();
        this.participantStatuses = new HashMap<>();
        this.reminders = new ArrayList<>();
        this.attachments = new ArrayList<>();
        this.recurrenceExceptions = new ArrayList<>();
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCalendarId() {
        return calendarId;
    }

    public void setCalendarId(String calendarId) {
        this.calendarId = calendarId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    public long getEndTime() {
        return endTime;
    }

    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }

    public boolean isAllDay() {
        return allDay;
    }

    public void setAllDay(boolean allDay) {
        this.allDay = allDay;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getRecurrenceRule() {
        return recurrenceRule;
    }

    public void setRecurrenceRule(String recurrenceRule) {
        this.recurrenceRule = recurrenceRule;
    }

    public List<Long> getRecurrenceExceptions() {
        return recurrenceExceptions;
    }

    public void setRecurrenceExceptions(List<Long> recurrenceExceptions) {
        this.recurrenceExceptions = recurrenceExceptions;
    }

    public String getInstanceOf() {
        return instanceOf;
    }

    public void setInstanceOf(String instanceOf) {
        this.instanceOf = instanceOf;
    }

    public List<String> getParticipantIds() {
        return participantIds;
    }

    public void setParticipantIds(List<String> participantIds) {
        this.participantIds = participantIds;
    }

    public Map<String, String> getParticipantStatuses() {
        return participantStatuses;
    }

    public void setParticipantStatuses(Map<String, String> participantStatuses) {
        this.participantStatuses = participantStatuses;
    }

    public List<Reminder> getReminders() {
        return reminders;
    }

    public void setReminders(List<Reminder> reminders) {
        this.reminders = reminders;
    }

    public List<Attachment> getAttachments() {
        return attachments;
    }

    public void setAttachments(List<Attachment> attachments) {
        this.attachments = attachments;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getVisibility() {
        return visibility;
    }

    public void setVisibility(String visibility) {
        this.visibility = visibility;
    }

    public void addParticipant(String uid, String status) {
        if (!participantIds.contains(uid)) {
            participantIds.add(uid);
        }
        participantStatuses.put(uid, status);
    }

    public void removeParticipant(String uid) {
        participantIds.remove(uid);
        participantStatuses.remove(uid);
    }

    public void addReminder(Reminder reminder) {
        if (reminders == null) {
            reminders = new ArrayList<>();
        }
        reminders.add(reminder);
    }

    public void addAttachment(Attachment attachment) {
        if (attachments == null) {
            attachments = new ArrayList<>();
        }
        attachments.add(attachment);
    }

    public void addRecurrenceException(long timestamp) {
        if (recurrenceExceptions == null) {
            recurrenceExceptions = new ArrayList<>();
        }
        recurrenceExceptions.add(timestamp);
    }

    public boolean isRecurring() {
        return recurrenceRule != null && !recurrenceRule.isEmpty();
    }

    public boolean isRecurringInstance() {
        return instanceOf != null && !instanceOf.isEmpty();
    }
}

